[versions]
agp = "9.0.0"
appcompat = "1.7.1"
gson = "2.13.2"
junit = "4.13.2"
lifecycleRuntime = "2.10.0"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
okhttp = "5.3.2"
recyclerview = "1.4.0"
webkit = "1.15.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleRuntime" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleRuntime" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleRuntime" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

[bundles]
# 将 Lifecycle 相关的库捆绑在一起
lifecycle = ["lifecycle-runtime", "lifecycle-viewmodel", "lifecycle-livedata"]
# 网络相关捆绑
network = ["okhttp", "gson"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
